### ISSUE TITLE
Cannot openstream due to credential mode is 'include' when creating an EventSource

### ISSUE THREAD

**Issue by rmaroun** [streamdataio/streamdataio-js#3]
I am getting the following message from the browser when trying to open a data stream:

> XMLHttpRequest cannot load https://streamdata.motwin.net/XXXXX?X-Sd-Token=YYYYYYYY. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by dominiquemongelli** [comment]
As discussed with @rmaroun by email, the issues was due to bad import in the javascript.
The react app done by @rmaroun  included nodejs libraries whereas JS SDK library must be used for web app: 
Was:
```javascript
import {StreamDataIo} from 'streamdataio-js-sdk/dist/bundles/streamdataio-node';
import jsonpatch from 'fast-json-patch';
```
Must be: 
```javascript
import {StreamDataIo} from 'streamdataio-js-sdk';
import jsonpatch from 'fast-json-patch';
```
